/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_fensan_android_jnidemo_MainActivity */

#ifndef _Included_co_fensan_android_jnidemo_MainActivity
#define _Included_co_fensan_android_jnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_fensan_android_jnidemo_MainActivity
 * Method:    sayHelloByJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_co_fensan_android_jnidemo_MainActivity_sayHelloByJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
